version: "3.9"

services:
  app:
    image: golang:1.23.4
    container_name: go-app
    working_dir: /workspace
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=exampledb

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # volumes:
    #   - db_data:/var/lib/mysql
    volumes: # Directamente que ejecute el create-tables del ejemplo de la base de datos
      - ./getting-started/acceso_db/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
    

volumes:
  db_data: 
